config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :movies, only: %i[index create]
  resources :posts do
    resources :qr_codes, only: :create
  end

  resources :tasks, only: %i[index show] do
    namespace :assignments do
      resources :multiples, only: :create
    end
    resources :assignments, only: :create
    resources :checklist_items, only: [:index]
    resources :notes, only: :create
  end
  resources :notes, only: :index
  resources :checklist_items, only: :update
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :manager, class_name: 'User'
  has_many :assignments
  has_many :contributors, through: :assignments
  has_many :checklist_items, dependent: :destroy
  has_many :notes, dependent: :destroy
  validates :name, :manager, :expected_end_date, :capacity, presence: true

  def checklist_items_completed
    checklist_items.where(completed: true)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all.order(created_at: :asc)
    @assignment = Assignment.new
    @users = User.all
  end

  def show
    @task = Task.find(params[:id])
    @notes = @task.notes.order(created_at: :desc)
    @assignment = Assignment.new
    @note = Note.new
    # @checklist_items_completed = @task.checklist_items_completed
  end
end

app/views/tasks/_assignments.html.erb
<div class="assignments postion-relative" style='margin-bottom: 2rem;'>
  <% @task.assignments.each_with_index do |assignment, index| %>
    <%= image_tag "https://kitt.lewagon.com/placeholder/users/#{assignment.contributor.nickname}", class: "avatar #{'over-user' if index < @task.assignments.size}" %>

  <% end %>
  <!-- Button trigger modal -->
  <%= button_tag '+', type: 'button',
                      data: {
                        bs_toggle: 'modal',
                        bs_target: '#exampleModal'
                      },
                      class: 'btn__plus',
                      style: 'margin-left: 1rem;' %>
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <div class="modal-header__content">
            <h5 class="modal-title" id="exampleModalLabel"><%= @task.name %></h5>
            <div class="modal-header__sub-title">
              <p class='modal-title__sub'>
                <%= @task.expected_end_date.strftime('%d/%m') %>
              </p>
              <span class='dot'></span>
              <div class="limit-date">
                <%= icon('far','clock') %>
                <p>
                  <%= @task.expected_end_date.strftime('%H:%M') %>
                </p>
              </div>
            </div>
          </div>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <%= simple_form_for [@task, @assignment] do |f| %>
          <% if @assignment.errors.any? %>
            <%= flash[:alert] = @assignment.errors.messages %>
          <% end %>
          <div class="modal-body">
            <%= f.collection_check_boxes :contributor, User.available(@task), :id, :nickname do |b| %>
              <%# <%= raise %>
              <%= b.label(class: 'row align-items-center') { render 'assignments/contributor', b: b } %>
            <% end %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <%= f.submit class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_board.html.erb
<div class="board" data-controller='task-board'>
  <div class="board__sections">
    <ul>
      <% %w[ Task File Activity ].each do |section| %>
        <%= content_tag :li, section.capitalize, class: "#{'active active-hover' if section == 'Task'}", data: { action: 'click->task-board#changeSection', task_board_target: 'section'} %>
      <% end %>
    </ul>
  </div>
  <div class="section" data-controller='filter'  data-filter-url-value='<%= task_checklist_items_path(task) %>'>
    <div class="section__header">
      <div class="section__header_title">
        <span class='filter'>
          <i class="fas fa-sort" data-action='click->filter#display'></i>
          <div class="filter__pop input--hide"
                data-filter-target='popup'
                data-action='mouseleave->filter#hide'>
            <%= button_tag 'Completed', type: 'button', class: 'clean_button', data: { action: 'click->filter#update',  } %>
          </div>
        </span>
        <h3>Checklist</h3>
        <%= button_tag '+', type: 'button', class: 'btn__plus' %>
      </div>
      <%= form_tag task_checklist_items_path(task), method: :get do %>
        <%= text_field_tag :filter, params[:filter], placeholder: 'Search...' %>
      <% end %>
    </div>
    <div class="section__content" style="margin-bottom: 2.5rem;">
      <ul data-controller='sortable' data-filter-target='list'>
        <%= render 'checklist_items/index', checklist_items: task.checklist_items %>
      </ul>
    </div>
    <div class="section__notes">
      <div class="section__header">
        <div class="section__header_title note">
          <h3>Notes</h3>
          <%= button_tag '+', type: 'button', class: 'btn__plus', data: { bs_toggle: "modal",  bs_target:"#noteModal" } %>
        </div>

        <div class="modal fade" id="noteModal" tabindex="-1" aria-labelledby="noteModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header note">
                <h5 class="modal-title" id="noteModalLabel">New note</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <%= simple_form_for [@task, @note] do |f| %>
                <div class="modal-body">
                  <div class="row mb-3">
                    <div class="col-1">
                      <%= f.label :title, required: true %>
                    </div>
                    <div class="col-11">
                      <%= f.input :title, label: false %>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-1">
                      <%= f.label :rich_body, required: true %>
                    </div>
                    <div class="col-11">
                      <%= f.rich_text_area :rich_body %>
                    </div>
                  </div>
                </div>
                <div class="modal-footer">
                  <%# <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button> %>
                  <%= f.submit class: 'btn__note' %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="section__content">
        <ul>
          <%= render @notes %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_progress_bar.html.erb
<div class="checklist__bar" style='margin-bottom: 1rem'>
  <% checklist_size = task.checklist_items.size %>
  <% task.checklist_items.order(completed: :desc).each do |item| %>
    <div class='bar__step <%= 'bar__step-completed' if item.completed %>'
          style="width: <%= 100.fdiv(checklist_size).round(2) %>%;"
          aria-valuenow='<%= 100.fdiv(checklist_size).round(2) %>'
          aria-valuemin="0"
          aria-valuemax="100"></div>
  <% end %>
</div>
<div class="d-flex justify-content-between align-items" style='margin-bottom: 2rem;'>
  <div class="icons">
    <i class="fas fa-bars bars-icon"></i>
    <i class="fas fa-check check-icon"></i>
    <span data-update-checklist-item-target='amount'><%= @task.checklist_items_completed.size %>/<%= checklist_size %></span>
  </div>
  <p class='mb-0'>Due <%= time_ago_in_words(task.expected_end_date) %></p>
</div>

app/views/tasks/_task.html.erb
<div class="content__header" data-update-checklist-item-target='container'>
  <h1>Create brand mood boards</h1>
  <p class='text-muted'>Assemble three distinct mood boards for client consideration</p>
</div>
<%= render 'tasks/assignments', task: @task, assignment: @assignment %>

<%= render 'tasks/progress_bar', checklist_size: @checklist_size, task: @task, checklist_items_completed: @checklist_items_completed %>

<%= render 'tasks/board', task: @task %>

app/views/tasks/_task_row.html.erb
<!-- Modal -->
<div class="modal fade" id="<%= dom_id(task) %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <div class="modal-header__content">
          <h5 class="modal-title" id="exampleModalLabel"><%= task.name %></h5>
          <div class="modal-header__sub-title">
            <p class='modal-title__sub'>
              <%= task.expected_end_date.strftime('%d/%m') %>
            </p>
            <span class='dot'></span>
            <div class="limit-date">
              <%= icon('far','clock') %>
              <p>
                <%= task.expected_end_date.strftime('%H:%M') %>
              </p>
            </div>
          </div>
        </div>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= simple_form_for [task, @assignment], remote: true do |f| %>
        <div class="modal-body">
          <% @users.each do |user| %>
            <div class="row align-items-center">
              <div class="col-2">
                <%= image_tag "https://kitt.lewagon.com/placeholder/users/#{user.nickname}", class: 'avatar-large' %>
              </div>
              <div class="col-4">
                <p class="mb-0"><%= user.name %></p>
              </div>
              <div class="col-4">
                <p class="mb-0"><%= user.nickname %></p>
              </div>
              <div class="col-2" data-controller='fill-check-box'>
                <%= f.association :contributor,
                                  as: :check_boxes,
                                  wrapper_html: {
                                    class: 'input--hide'
                                  },
                                  input_html: {
                                    data: {
                                      fill_check_box_target: 'realInput'
                                    }
                                  } %>
                <input type="checkbox"
                       name="user"
                       data-action='change->fill-check-box#updateInput'
                       value="<%= user.id %>"
                       id="<%= dom_id(user) %>">
              </div>
            </div>
          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <%# <button type="button" class="btn btn-primary">Save changes</button> %>
          <%= f.submit "Assign contributors", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>

app/views/tasks/_top_menu.html.erb
<div class="d-flex bg-white w-100 mr-0 py-2 px-3 justify-content-between align-items-center border-bottom">
  <div class="col-11">
    <%= link_to 'Home', '#' %> >
    <%= link_to 'Project', '#' %> >
    <%= link_to 'Task', '#' %>
  </div>
  <div class="col-1 text-end">
    <%= button_tag type: "button", style: 'padding: 3px 8px; border-radius: 100%; background-color: lightgrey; border: 1px solid transparent; color: black', id: "dropdownMenuButton1", data: { bs_toggle: "dropdown" }, aria: { expanded: "false" } do %>
      <i class="fas fa-cog"></i>
    <% end %>

    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
      <li><a class="dropdown-item" href="#">Action</a></li>
      <li><a class="dropdown-item" href="#">Another action</a></li>
      <li><a class="dropdown-item" href="#">Something else here</a></li>
    </ul>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <table>
    <thead>
      <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Manager</th>
        <th>Capacity</th>
        <th>Contributors</th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <tr class='task-row'>
          <td><%= task.id %></td>
          <td><%= task.name %></td>
          <td><%= task.manager.email %></td>
          <td><%= task.capacity %></td>
          <td><%= task.assignments.size %></td>
          <td><%= link_to 'show', task_path(task) %></td>
          <td><%#= link_to 'Assign contributor', '#', remote: true, data: { bs_toggle: "modal", bs_target: "#task_#{task.id}" } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tasks/show.html.erb
<div class="menu-layout">
  <%= render 'shared/menu' %>
  <div class="content">
    <%= render 'tasks/top_menu' %>
    <div class="task__content" data-controller='update-checklist-item'>
      <%= render 'tasks/task', checklist_size: @checklist_size, task: @task, assignment: @assignment %>
  </div>

</div>