config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :movies, only: %i[index create]
  resources :posts do
    resources :qr_codes, only: :create
  end

  resources :tasks, only: %i[index show] do
    namespace :assignments do
      resources :multiples, only: :create
    end
    resources :assignments, only: :create
    resources :checklist_items, only: [:index]
    resources :notes, only: :create
  end
  resources :notes, only: :index
  resources :checklist_items, only: :update
end

app/models/post.rb
require 'open-uri'

class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :qr_code
  after_create :qr_code_job

  def qr_code_job
    QrCodeJob.perform_later self
  end

  def attach_qr_code
    generate_upload_and_attach_new_qr_code
  end

  private

  def generate_upload_and_attach_new_qr_code
    qr = RQRCode::QRCode.new(url)
    png_qr_code = qr.as_png
    file = StringIO.new(png_qr_code.to_s)
    @cloud_response = Cloudinary::Uploader.upload(file)
    attach_qr_code_and_email_it
  end

  def attach_qr_code_and_email_it
    qr_code.attach(
      io: URI.open(@cloud_response['secure_url']),
      filename: "#{title.gsub(/\W/, '_')}.png",
      content_type: 'image/png'
    )
    # SEND EMAIL
    QrCodeMailer.with(qr_code_url: @cloud_response['secure_url'], user: user)
                .new_qr_code_mail
                .deliver_later
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      PostMailer.with(user: current_user).new_post_mail.deliver_later

      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      PostMailer.with(user: current_user).update_post_mail.deliver_later

      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    PostMailer.with(user: current_user).destroy_post_mail.deliver_later

    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :url)
  end
end

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.url %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'QR Code', post_qr_codes_path(post), method: :post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @post.url %>
</p>

<% if @post.qr_code.attached? %>
  <p>
    <strong>QR Code:</strong>
  </p>
  <%= cl_image_tag @post.qr_code.key, height: 300, width: 300, crop: :fill %>
<% end %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>